/* ============================================================
   BIOWATCH-AI — EVIDENCE / EPISTEMIC STATUS VOCABULARY
   ------------------------------------------------------------
   Every quantitative or qualitative statement rendered by this
   prototype MUST carry one of these tags. This module is the
   single source of truth for that vocabulary.
   ============================================================ */

export const EVIDENCE = {
  ESTABLISHED: {
    key: 'ESTABLISHED',
    label: 'ESTABLISHED',
    color: 'var(--color-ev-established)',
    definition:
      'Supported by peer-reviewed literature or by an authoritative public-health source that is cited inline. Not produced by this prototype.',
  },
  ASSUMPTION: {
    key: 'ASSUMPTION',
    label: 'ASSUMPTION',
    color: 'var(--color-ev-assumption)',
    definition:
      'A design or modelling premise adopted for the prototype. Explicitly not verified. Must be revisited before any research claim.',
  },
  HYPOTHESIS: {
    key: 'HYPOTHESIS',
    label: 'HYPOTHESIS',
    color: 'var(--color-ev-hypothesis)',
    definition:
      'A testable proposition the research programme intends to evaluate. No supporting result exists yet.',
  },
  PRELIMINARY: {
    key: 'PRELIMINARY',
    label: 'PRELIMINARY',
    color: 'var(--color-ev-preliminary)',
    definition:
      'An early, non-validated observation from an incomplete or unreviewed procedure. Not citable. May change or be withdrawn.',
  },
  PREDICTION: {
    key: 'PREDICTION',
    label: 'PREDICTION',
    color: 'var(--color-ev-prediction)',
    definition:
      'A model-generated output about unobserved values. A prediction is not a biological confirmation and not a public-health determination.',
  },
  PLAN: {
    key: 'PLAN',
    label: 'PLAN',
    color: 'var(--color-ev-plan)',
    definition:
      'Intended future work. Describes what the module is designed to do once implemented; nothing has been executed.',
  },
  SIMULATED: {
    key: 'SIMULATED',
    label: 'SIMULATED',
    color: 'var(--color-ev-simulated)',
    definition:
      'Synthetic values generated by a deterministic function inside this prototype for interface demonstration. Contains no real-world surveillance information.',
  },
};

export const EVIDENCE_ORDER = [
  'ESTABLISHED', 'ASSUMPTION', 'HYPOTHESIS', 'PRELIMINARY',
  'PREDICTION', 'PLAN', 'SIMULATED',
];

/* ------------------------------------------------------------
   Standard interface strings. Centralised so that scientifically
   irresponsible phrasing cannot drift into individual modules.
   ------------------------------------------------------------ */
export const SAFE_LANGUAGE = {
  simulatedBanner: 'SIMULATED DATA — FOR PROTOTYPE DEMONSTRATION ONLY',
  simulatedShort: 'SIMULATED DATA — NOT REAL-WORLD SURVEILLANCE',
  notImplemented: 'RESEARCH MODULE — NOT YET IMPLEMENTED',
  connectorUnconfigured: 'CONNECTOR NOT CONFIGURED',
  connectorAvailable: 'LIVE CONNECTOR AVAILABLE — CONFIGURATION REQUIRED',
  awaitingExperiment: 'Awaiting experiment',
  demoMetric: 'Demo metric',
  noData: 'DATA NOT AVAILABLE',
  causation: 'Correlation does not establish biological causation.',
  humanReview: 'Requires human review',
  notDiagnostic:
    'Research prototype. Not a clinical diagnostic device and not an operational public-health system.',
  insufficient: 'Evidence insufficient for confirmation',
};

/* Permitted signal phrasing — an outbreak is NEVER declared by the system. */
export const SIGNAL_PHRASES = [
  'Signal detected',
  'Unusual activity',
  'Elevated reporting',
  'Potential anomaly detected',
  'Requires investigation',
  'Model-generated alert',
  'Prediction — not biological confirmation',
];

export const ALERT_STATES = {
  GREEN: {
    key: 'GREEN',
    color: 'var(--color-alert-green)',
    title: 'No unusual activity detected',
    meaning:
      'Observed values fall inside the estimated baseline interval for this stream. Routine monitoring continues.',
  },
  YELLOW: {
    key: 'YELLOW',
    color: 'var(--color-alert-yellow)',
    title: 'Signal requiring review',
    meaning:
      'A deviation from baseline was flagged by at least one detector. Analyst triage requested. No epidemiological interpretation is implied.',
  },
  ORANGE: {
    key: 'ORANGE',
    color: 'var(--color-alert-orange)',
    title: 'Stronger signal requiring investigation',
    meaning:
      'Concordant deviation across detectors or streams. Structured investigation by a qualified analyst is requested.',
  },
  RED: {
    key: 'RED',
    color: 'var(--color-alert-red)',
    title: 'High-priority signal requiring human assessment',
    meaning:
      'Large, persistent, multi-stream deviation. Escalation to a qualified epidemiologist is requested. This is an interface state, NOT a public-health decision.',
  },
};

export const ALERT_DISCLAIMER =
  'Alert states are prototype interface states derived from statistical deviation. They are not medical or public-health decisions, and they do not constitute confirmation of an outbreak.';
