/* ============================================================
   BIOWATCH-AI — DOMAIN REGISTRIES
   Pathogen/stream/region definitions used across modules.
   Descriptive fields cite public-health convention (ESTABLISHED);
   all numeric activity is generated by lib/synth.js (SIMULATED).
   ============================================================ */

export const STREAMS = {
  epi:      { key: 'epi',      label: 'Epidemiological', color: 'var(--color-bw-primary)',  icon: 'Activity' },
  genomic:  { key: 'genomic',  label: 'Genomic',         color: 'var(--color-bw-genomic)',  icon: 'Dna' },
  env:      { key: 'env',      label: 'Environmental',   color: 'var(--color-bw-env)',      icon: 'Droplets' },
  lab:      { key: 'lab',      label: 'Laboratory',      color: 'var(--color-bw-lab)',      icon: 'FlaskConical' },
  synd:     { key: 'synd',     label: 'Syndromic',       color: 'var(--color-bw-data)',     icon: 'Thermometer' },
  event:    { key: 'event',    label: 'Event-based',     color: '#a98bd6',                  icon: 'Newspaper' },
};

/* Pathogen reference metadata.
   Transmission/seasonality notes are textbook-level public-health facts
   (ESTABLISHED). No case counts are stored here. */
export const PATHOGENS = [
  {
    id: 'influenza-a', name: 'Influenza A', family: 'Orthomyxoviridae',
    class: 'Respiratory virus', streams: ['epi', 'lab', 'synd', 'genomic'],
    seasonality: 'Marked winter seasonality in temperate zones; less regular in tropics.',
    note: 'Subtyping (e.g. H1/H3) and clade assignment are routine in sentinel networks.',
    surveillance: 'Sentinel ILI/ARI networks; virological confirmation by RT-PCR.',
  },
  {
    id: 'sars-cov-2', name: 'SARS-CoV-2', family: 'Coronaviridae',
    class: 'Respiratory virus', streams: ['epi', 'lab', 'genomic', 'env', 'synd'],
    seasonality: 'Multi-annual wave structure; seasonality not fully established.',
    note: 'Wastewater detection is an established complementary indicator in several countries.',
    surveillance: 'Case reporting, wastewater, genomic sequencing, hospital admissions.',
  },
  {
    id: 'cholera', name: 'Cholera (V. cholerae)', family: 'Vibrionaceae',
    class: 'Enteric bacterium', streams: ['epi', 'lab', 'env'],
    seasonality: 'Strongly linked to rainfall, flooding and water/sanitation conditions.',
    note: 'Rapid diagnostic tests require culture/PCR confirmation.',
    surveillance: 'Case-based reporting, culture confirmation, environmental water sampling.',
  },
  {
    id: 'lassa', name: 'Lassa fever (LASV)', family: 'Arenaviridae',
    class: 'Viral haemorrhagic fever', streams: ['epi', 'lab', 'genomic'],
    seasonality: 'Pronounced dry-season peak in West Africa (approx. Dec–Mar).',
    note: 'Rodent reservoir (Mastomys spp.); zoonotic spillover dominant.',
    surveillance: 'Case-based reporting with RT-PCR confirmation at reference laboratories.',
  },
  {
    id: 'mpox', name: 'Mpox (MPXV)', family: 'Poxviridae',
    class: 'Zoonotic virus', streams: ['epi', 'lab', 'genomic'],
    seasonality: 'No established regular seasonality.',
    note: 'Clade assignment is epidemiologically relevant.',
    surveillance: 'Case-based reporting, PCR confirmation, sequencing where capacity exists.',
  },
  {
    id: 'dengue', name: 'Dengue (DENV)', family: 'Flaviviridae',
    class: 'Arbovirus', streams: ['epi', 'lab', 'env'],
    seasonality: 'Rainfall- and temperature-dependent vector dynamics.',
    note: 'Four serotypes; serotype replacement affects severity patterns.',
    surveillance: 'Case reporting, NS1/PCR confirmation, entomological indices.',
  },
  {
    id: 'measles', name: 'Measles (MeV)', family: 'Paramyxoviridae',
    class: 'Vaccine-preventable virus', streams: ['epi', 'lab', 'genomic'],
    seasonality: 'Epidemic cycles governed by susceptible accumulation and contact patterns.',
    note: 'Immunity gaps are the dominant driver of resurgence.',
    surveillance: 'Case-based reporting with IgM/PCR confirmation; genotype surveillance.',
  },
  {
    id: 'amr-kpn', name: 'Carbapenem-resistant K. pneumoniae', family: 'Enterobacteriaceae',
    class: 'AMR organism', streams: ['lab', 'genomic'],
    seasonality: 'Not applicable — healthcare-associated transmission dynamics.',
    note: 'Resistance-gene surveillance (e.g. carbapenemase families) is laboratory-driven.',
    surveillance: 'Laboratory isolate reporting, susceptibility testing, genomic AMR typing.',
  },
];

/* Regions used for the map / regional aggregation.
   Coordinates are geographic reference points only. */
export const REGIONS = [
  { id: 'AFRO',  name: 'African Region',            lon: 20,   lat: 2 },
  { id: 'EMRO',  name: 'Eastern Mediterranean',     lon: 45,   lat: 25 },
  { id: 'EURO',  name: 'European Region',           lon: 15,   lat: 52 },
  { id: 'PAHO',  name: 'Region of the Americas',    lon: -75,  lat: 5 },
  { id: 'SEARO', name: 'South-East Asia',           lon: 95,   lat: 15 },
  { id: 'WPRO',  name: 'Western Pacific',           lon: 130,  lat: 10 },
];

/* Country reference points (geographic centroids, ESTABLISHED geography).
   Any activity value attached to these in DEMONSTRATION mode is SIMULATED. */
export const COUNTRY_POINTS = [
  { iso: 'NGA', name: 'Nigeria', lon: 8.7, lat: 9.1, region: 'AFRO' },
  { iso: 'GHA', name: 'Ghana', lon: -1.0, lat: 7.9, region: 'AFRO' },
  { iso: 'ZAF', name: 'South Africa', lon: 24.7, lat: -29.0, region: 'AFRO' },
  { iso: 'KEN', name: 'Kenya', lon: 37.9, lat: 0.0, region: 'AFRO' },
  { iso: 'ETH', name: 'Ethiopia', lon: 39.8, lat: 9.1, region: 'AFRO' },
  { iso: 'COD', name: 'DR Congo', lon: 23.6, lat: -2.9, region: 'AFRO' },
  { iso: 'EGY', name: 'Egypt', lon: 30.8, lat: 26.8, region: 'EMRO' },
  { iso: 'PAK', name: 'Pakistan', lon: 69.3, lat: 30.4, region: 'EMRO' },
  { iso: 'GBR', name: 'United Kingdom', lon: -3.4, lat: 55.4, region: 'EURO' },
  { iso: 'DEU', name: 'Germany', lon: 10.5, lat: 51.2, region: 'EURO' },
  { iso: 'FRA', name: 'France', lon: 2.2, lat: 46.2, region: 'EURO' },
  { iso: 'ITA', name: 'Italy', lon: 12.6, lat: 41.9, region: 'EURO' },
  { iso: 'USA', name: 'United States', lon: -98.6, lat: 39.8, region: 'PAHO' },
  { iso: 'BRA', name: 'Brazil', lon: -51.9, lat: -14.2, region: 'PAHO' },
  { iso: 'MEX', name: 'Mexico', lon: -102.6, lat: 23.6, region: 'PAHO' },
  { iso: 'IND', name: 'India', lon: 78.9, lat: 20.6, region: 'SEARO' },
  { iso: 'IDN', name: 'Indonesia', lon: 113.9, lat: -0.8, region: 'SEARO' },
  { iso: 'THA', name: 'Thailand', lon: 100.9, lat: 15.9, region: 'SEARO' },
  { iso: 'JPN', name: 'Japan', lon: 138.3, lat: 36.2, region: 'WPRO' },
  { iso: 'PHL', name: 'Philippines', lon: 121.8, lat: 12.9, region: 'WPRO' },
  { iso: 'AUS', name: 'Australia', lon: 133.8, lat: -25.3, region: 'WPRO' },
  { iso: 'CHN', name: 'China', lon: 104.2, lat: 35.9, region: 'WPRO' },
];

/* Nigerian states used by the Nigeria/Africa module (geography only). */
export const NIGERIA_STATES = [
  { id: 'LA', name: 'Lagos', lon: 3.4, lat: 6.5, zone: 'South West' },
  { id: 'FC', name: 'FCT Abuja', lon: 7.4, lat: 9.1, zone: 'North Central' },
  { id: 'KN', name: 'Kano', lon: 8.5, lat: 12.0, zone: 'North West' },
  { id: 'RI', name: 'Rivers', lon: 6.9, lat: 4.8, zone: 'South South' },
  { id: 'ED', name: 'Edo', lon: 5.9, lat: 6.6, zone: 'South South' },
  { id: 'ON', name: 'Ondo', lon: 5.1, lat: 7.1, zone: 'South West' },
  { id: 'EB', name: 'Ebonyi', lon: 8.1, lat: 6.3, zone: 'South East' },
  { id: 'BO', name: 'Borno', lon: 13.1, lat: 11.8, zone: 'North East' },
  { id: 'BA', name: 'Bauchi', lon: 10.0, lat: 10.3, zone: 'North East' },
  { id: 'TA', name: 'Taraba', lon: 10.8, lat: 8.0, zone: 'North East' },
  { id: 'PL', name: 'Plateau', lon: 9.5, lat: 9.2, zone: 'North Central' },
  { id: 'OY', name: 'Oyo', lon: 3.9, lat: 8.2, zone: 'South West' },
];
