/* ============================================================
   BIOWATCH-AI — SYNTHETIC DATA ENGINE
   ------------------------------------------------------------
   EVERY value produced here is SIMULATED. It is generated by a
   deterministic seeded PRNG so that the interface is reproducible
   across reloads and reviewers.
   It encodes NO real-world epidemiological information, NO real
   outbreak, NO real country statistic and NO real model result.
   Components consuming this module must render the SIMULATED tag.
   ============================================================ */

export const SYNTHETIC_PROVENANCE = {
  generator: 'bw-synth v0.4 (mulberry32 PRNG + seasonal-Poisson surrogate)',
  seedPolicy: 'Deterministic per stream key; identical on every load.',
  statement:
    'Synthetic surrogate series. Structure (weekly seasonality, reporting-delay decay, occasional step change) is imposed by the generator, not observed in nature.',
  notCitable: 'Not citable. Not derived from WHO, CDC, ECDC, NCBI or any real repository.',
};

/* --- deterministic PRNG ----------------------------------- */
export function seedFrom(str) {
  let h = 1779033703 ^ String(str).length;
  for (let i = 0; i < String(str).length; i++) {
    h = Math.imul(h ^ String(str).charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  return h >>> 0;
}

export function rng(seed) {
  let a = typeof seed === 'string' ? seedFrom(seed) : seed >>> 0;
  return function () {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function gauss(r) {
  const u = Math.max(1e-9, r()), v = Math.max(1e-9, r());
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

export function isoWeeksBack(n, end = new Date('2026-08-17T00:00:00Z')) {
  const out = [];
  for (let i = n - 1; i >= 0; i--) {
    const d = new Date(end.getTime() - i * 7 * 86400000);
    out.push(d.toISOString().slice(0, 10));
  }
  return out;
}

/**
 * SIMULATED weekly count series with:
 *  - annual seasonality
 *  - slow trend
 *  - negative-binomial-ish overdispersion
 *  - optional injected step change (a synthetic "signal" for UI demo)
 */
export function synthSeries(key, {
  weeks = 104, level = 120, season = 0.45, trend = 0.0,
  disp = 0.18, injectAt = null, injectSize = 0, phase = 0,
} = {}) {
  const r = rng(key);
  const dates = isoWeeksBack(weeks);
  const out = [];
  for (let i = 0; i < weeks; i++) {
    const woy = (i + phase) % 52;
    const s = 1 + season * Math.sin((2 * Math.PI * woy) / 52 - Math.PI / 3);
    const tr = 1 + trend * (i / weeks);
    let mu = level * s * tr;
    if (injectAt !== null && i >= weeks - injectAt) {
      const k = (i - (weeks - injectAt) + 1) / Math.max(1, injectAt);
      mu *= 1 + injectSize * Math.min(1, k * 1.6);
    }
    const noise = 1 + disp * gauss(r) * 0.6;
    const value = Math.max(0, Math.round(mu * noise));
    /* baseline = seasonal expectation WITHOUT the injected step */
    const base = Math.round(level * s * tr);
    const sd = Math.max(1.5, Math.sqrt(base) * 1.35 + base * disp * 0.55);
    out.push({
      date: dates[i],
      week: `W${String((woy % 52) + 1).padStart(2, '0')}`,
      value,
      baseline: base,
      lo: Math.max(0, Math.round(base - 1.96 * sd)),
      hi: Math.round(base + 1.96 * sd),
      z: +((value - base) / sd).toFixed(2),
    });
  }
  return out;
}

/** Reporting-delay distribution (SIMULATED) — share of reports arriving after d weeks */
export function synthDelayProfile(key, maxLag = 6) {
  const r = rng(key + ':delay');
  const raw = Array.from({ length: maxLag + 1 }, (_, d) => Math.exp(-d / (0.9 + r())) * (0.7 + 0.6 * r()));
  const sum = raw.reduce((a, b) => a + b, 0);
  return raw.map((v, d) => ({ lag: d, share: +(v / sum).toFixed(3) }));
}

/** Small helper for sparkline-style arrays */
export function tail(series, n) { return series.slice(Math.max(0, series.length - n)); }

export function fmtNum(n) {
  if (n === null || n === undefined || Number.isNaN(n)) return '—';
  if (Math.abs(n) >= 1e9) return (n / 1e9).toFixed(1) + 'B';
  if (Math.abs(n) >= 1e6) return (n / 1e6).toFixed(1) + 'M';
  if (Math.abs(n) >= 1e4) return (n / 1e3).toFixed(0) + 'k';
  return String(n);
}

export function fmtTs(d = new Date()) {
  return new Date(d).toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
}
