/* ============================================================
   BIOWATCH-AI — RESEARCH DECISION LOG (SEGMENT 10)
   Append-only record of design and methodological decisions.
   Superseded entries remain visible. Nothing is ever deleted.
   ============================================================ */
import { useMemo, useState } from 'react';
import * as Icons from 'lucide-react';
import {
  PageHeader, Panel, Pill, EvidenceTag, Callout, Grid, Table, Btn, Segmented,
  KV, Stat, Field, Input, Select,
} from '../components/ui';
import { fmtTs } from '../lib/synth';

const DECISIONS = [
  {
    id: 'DEC-001', date: '2026-07-02', area: 'Scope',
    decision: 'BIOWATCH-AI is scoped as a research and educational prototype, not an operational surveillance system.',
    reason: 'Operational systems require validation, institutional mandate, data agreements and accountability structures the project does not have.',
    evidence: 'Project charter; absence of institutional mandate.',
    alternative: 'Pursue an operational pilot with a partner agency.',
    status: 'ACTIVE',
  },
  {
    id: 'DEC-002', date: '2026-07-05', area: 'Methodology',
    decision: 'No machine-learning result may be displayed without an accompanying statistical baseline evaluated on the same temporal split.',
    reason: 'A model metric without a comparator is uninterpretable, and the literature contains many surveillance ML claims that do not beat simple baselines.',
    evidence: 'Established practice in forecasting evaluation; internal design review.',
    alternative: 'Report model metrics alone and add baselines later.',
    status: 'ACTIVE',
  },
  {
    id: 'DEC-003', date: '2026-07-09', area: 'Interface',
    decision: 'The system may never emit the phrase "outbreak confirmed" or any equivalent. Permitted phrasing is restricted to a fixed vocabulary of signal terms.',
    reason: 'Interface language becomes the claim. Constraining vocabulary structurally prevents overstatement.',
    evidence: 'Risk analysis of alert phrasing; safety rule in the project specification.',
    alternative: 'Allow analysts to write free-text conclusions.',
    status: 'ACTIVE',
  },
  {
    id: 'DEC-004', date: '2026-07-14', area: 'Data',
    decision: 'Unconfigured connectors display CONNECTOR NOT CONFIGURED and are never substituted with synthetic values.',
    reason: 'Silently filling a live panel with synthetic data is the single most dangerous failure mode for a surveillance dashboard.',
    evidence: 'Design review; prototype safety rules.',
    alternative: 'Show synthetic placeholders in live mode for visual completeness.',
    status: 'ACTIVE',
  },
  {
    id: 'DEC-005', date: '2026-07-20', area: 'Metrics',
    decision: 'Accuracy is excluded from the metric contract. Sensitivity, PPV, alarm rate and detection delay must be reported jointly.',
    reason: 'Under the class imbalance typical of outbreak detection, accuracy is dominated by true negatives and is actively misleading.',
    evidence: 'Standard result in imbalanced classification; documented in the Model Evaluation module.',
    alternative: 'Report accuracy alongside other metrics with a caveat.',
    status: 'ACTIVE',
  },
  {
    id: 'DEC-006', date: '2026-07-28', area: 'Biological data',
    decision: 'No nucleotide or amino-acid sequence, mutation call or variant discovery is generated by the prototype, even under a SIMULATED label.',
    reason: 'Molecular outputs carry unearned authority and are readily mistaken for findings; the reputational and scientific cost of confusion exceeds the demonstration value.',
    evidence: 'Biosecurity and integrity review.',
    alternative: 'Generate clearly-labelled synthetic sequences for visual demonstration.',
    status: 'ACTIVE',
  },
  {
    id: 'DEC-007', date: '2026-08-01', area: 'Labels',
    decision: 'Self-referential labels (baseline exceedance used as ground truth) are permitted for pipeline demonstration but are prohibited as evidence of detection ability.',
    reason: 'Training on a rule and then evaluating against that rule measures imitation, not detection.',
    evidence: 'Circularity analysis recorded in the ML Lab module.',
    alternative: 'Use exceedance labels as a provisional target until curated labels exist.',
    status: 'ACTIVE',
  },
  {
    id: 'DEC-008', date: '2026-08-06', area: 'Mortality data',
    decision: 'Mortality series are not synthesised in DEMONSTRATION mode; the mortality panel remains empty.',
    reason: 'Fabricated death counts are unacceptable even when labelled, and their absence costs the demonstration little.',
    evidence: 'Integrity review of the Disease Intelligence module.',
    alternative: 'Synthesise mortality with prominent labelling.',
    status: 'ACTIVE',
  },
  {
    id: 'DEC-009', date: '2026-08-10', area: 'Architecture',
    decision: 'Detection thresholds default to k = 2 with a 2-week persistence rule.',
    reason: 'Chosen to make the interface demonstrable; not derived from any operational alarm-rate budget.',
    evidence: 'None — this is an arbitrary demonstration parameter and is recorded as such.',
    alternative: 'Leave thresholds unset and require explicit user configuration.',
    status: 'PROVISIONAL — TO BE REPLACED BY AN AGREED ALARM BUDGET',
  },
  {
    id: 'DEC-010', date: '2026-07-11', area: 'Interface',
    decision: 'Country choropleth fill encodes detector state only.',
    reason: 'Encoding case counts by colour invites comparison between territories with incomparable surveillance capacity.',
    evidence: 'Cartographic review.',
    alternative: 'Encode incidence rate per 100,000.',
    status: 'SUPERSEDED BY DEC-011',
  },
  {
    id: 'DEC-011', date: '2026-08-15', area: 'Interface',
    decision: 'Map adds an explicit hatched "insufficient data" fill, distinct from "no unusual activity".',
    reason: 'Rendering missing data in the same colour as a green state told the reviewer that nothing was happening where in fact nothing was known.',
    evidence: 'Usability review of the surveillance map; supersedes DEC-010.',
    alternative: 'Grey-out with a legend note only.',
    status: 'ACTIVE',
  },
];

const STATUS_COLOR = (s) =>
  s.startsWith('ACTIVE') ? 'var(--color-alert-green)'
    : s.startsWith('PROVISIONAL') ? 'var(--color-alert-yellow)'
    : 'var(--color-bw-dim)';

export default function Decisions() {
  const [area, setArea] = useState('all');
  const [q, setQ] = useState('');
  const [sel, setSel] = useState('DEC-011');

  const areas = ['all', ...Array.from(new Set(DECISIONS.map((d) => d.area)))];
  const rows = DECISIONS
    .filter((d) => area === 'all' || d.area === area)
    .filter((d) => !q || (d.decision + d.reason + d.id).toLowerCase().includes(q.toLowerCase()))
    .sort((a, b) => b.date.localeCompare(a.date));
  const cur = DECISIONS.find((d) => d.id === sel);

  return (
    <>
      <PageHeader kicker="Module 18" title="Research Decision Log" evidence="ESTABLISHED"
        description="Append-only record of every significant design and methodological decision, with the reasoning, the evidence, the alternative that was rejected, and the current status. Superseded decisions remain visible." />

      <Callout tone="info" title="Why superseded entries are never deleted" icon={<Icons.History size={12} />}>
        A decision log that only shows current decisions is a marketing document. Keeping DEC-010 visible next to
        the decision that replaced it records that the earlier design was wrong and why — which is the part a
        reviewer, supervisor or future contributor actually needs.
      </Callout>

      <Grid cols="sm:grid-cols-2 xl:grid-cols-4" className="my-3">
        <Stat label="Decisions recorded" value={DECISIONS.length} evidence="ESTABLISHED" />
        <Stat label="Active" value={DECISIONS.filter((d) => d.status.startsWith('ACTIVE')).length} evidence="ESTABLISHED" color="var(--color-alert-green)" />
        <Stat label="Provisional" value={DECISIONS.filter((d) => d.status.startsWith('PROVISIONAL')).length} evidence="ESTABLISHED" color="var(--color-alert-yellow)" />
        <Stat label="Superseded (retained)" value={DECISIONS.filter((d) => d.status.startsWith('SUPERSEDED')).length} evidence="ESTABLISHED" color="var(--color-bw-muted)" />
      </Grid>

      <Grid cols="xl:grid-cols-[1fr_420px]">
        <Panel title="Decision register" evidence="ESTABLISHED"
          actions={
            <div className="flex flex-wrap items-center gap-2">
              <Input value={q} onChange={setQ} placeholder="Search…" className="w-[140px]" />
              <Select value={area} onChange={setArea} className="w-[130px]"
                options={areas.map((a) => ({ value: a, label: a === 'all' ? 'All areas' : a }))} />
            </div>}>
          <Table rowKey="id" columns={[
            { key: 'id', header: 'ID', render: (r) => (
              <button className="bw-num text-[10.5px] text-bw-text hover:text-bw-primary-bright" onClick={() => setSel(r.id)}>{r.id}</button>) },
            { key: 'date', header: 'Date', render: (r) => <span className="bw-num text-[10.5px] text-bw-dim">{r.date}</span> },
            { key: 'area', header: 'Area', render: (r) => <Pill color="var(--color-bw-line2)">{r.area}</Pill> },
            { key: 'decision', header: 'Decision', render: (r) => <span className="text-[11.5px]">{r.decision}</span> },
            { key: 'status', header: 'Status', align: 'right', render: (r) => (
              <span className="font-mono text-[8.5px] tracking-[0.08em]" style={{ color: STATUS_COLOR(r.status) }}>{r.status}</span>) },
          ]} rows={rows} />
        </Panel>

        <div className="flex min-w-0 flex-col gap-3">
          {cur && (
            <Panel title={`${cur.id} — detail`} evidence="ESTABLISHED" accent={STATUS_COLOR(cur.status)}>
              <KV cols={1} mono={false} items={[
                { k: 'Date', v: cur.date },
                { k: 'Area', v: cur.area, mono: false },
                { k: 'Decision', v: cur.decision, mono: false },
                { k: 'Reason', v: cur.reason, mono: false },
                { k: 'Evidence', v: cur.evidence, mono: false },
                { k: 'Alternative considered', v: cur.alternative, mono: false },
                { k: 'Status', v: cur.status, mono: false },
              ]} />
            </Panel>
          )}

          <Panel title="Log properties" evidence="ESTABLISHED">
            <KV items={[
              { k: 'Mutability', v: 'Append-only' },
              { k: 'Deletion', v: 'Not permitted at any role level' },
              { k: 'Supersession', v: 'New entry references the entry it replaces' },
              { k: 'Required fields', v: 'date · decision · reason · evidence · alternative · status' },
              { k: 'Empty evidence allowed?', v: 'Yes — recorded explicitly as "None"' },
              { k: 'Export', v: 'Markdown / JSON' },
            ]} />
            <Btn size="sm" className="mt-2 w-full" onClick={() => {
              const md = DECISIONS.map((d) =>
                `## ${d.id} — ${d.decision}\n\n- **Date:** ${d.date}\n- **Area:** ${d.area}\n- **Reason:** ${d.reason}\n- **Evidence:** ${d.evidence}\n- **Alternative considered:** ${d.alternative}\n- **Status:** ${d.status}\n`).join('\n');
              const blob = new Blob([`# BIOWATCH-AI — Research Decision Log\n\nExported ${fmtTs()}\n\n${md}`], { type: 'text/markdown' });
              const a = document.createElement('a'); a.href = URL.createObjectURL(blob);
              a.download = 'biowatch-decision-log.md'; a.click();
            }}>
              <Icons.Download size={12} /> Export decision log (Markdown)
            </Btn>
          </Panel>

          <Panel title="Add decision" evidence="PLAN">
            <p className="mb-2 text-[11px] leading-relaxed text-bw-muted">
              In the deployed system, new entries are written through an authenticated endpoint and signed with the
              author identity. This prototype has no backend, so the form is disabled rather than pretending to persist.
            </p>
            <div className="space-y-2 opacity-50">
              <Field label="Decision"><Input value="" onChange={() => {}} placeholder="Disabled — no backend" /></Field>
              <Field label="Reason"><Input value="" onChange={() => {}} placeholder="Disabled — no backend" /></Field>
              <Btn disabled className="w-full"><Icons.Plus size={12} /> Append entry</Btn>
            </div>
          </Panel>
        </div>
      </Grid>
    </>
  );
}
