/* ============================================================
   BIOWATCH-AI — GENOMIC SURVEILLANCE (SEGMENT 8)
   ------------------------------------------------------------
   HARD RULE FOR THIS MODULE: no nucleotide/protein sequence, no
   real lineage name, no mutation and no variant discovery is
   fabricated anywhere. Synthetic lineages carry deliberately
   non-real placeholder labels (SYN-A … SYN-E) so that no output
   can be mistaken for a genomic finding.
   ============================================================ */
import { useMemo, useState } from 'react';
import * as Icons from 'lucide-react';
import {
  PageHeader, Panel, Pill, EvidenceTag, Callout, Grid, Table, Btn, Segmented,
  NotImplemented, SimulatedBanner, KV, Meter, Stat, NoData, Disclosure, Awaiting,
} from '../components/ui';
import { Stacked, Bars, Spark } from '../components/charts';
import WorldMap, { MapLegend } from '../components/WorldMap';
import { rng, synthSeries, isoWeeksBack, fmtTs } from '../lib/synth';
import { CONNECTORS } from '../lib/connectors';
import { SAFE_LANGUAGE } from '../lib/evidence';
import { useMode } from '../lib/mode';

/* Placeholder lineage labels — intentionally NOT real nomenclature. */
const SYN_LINEAGES = [
  { id: 'SYN-A', color: '#8b7ad6', note: 'Synthetic placeholder lineage A' },
  { id: 'SYN-B', color: '#4a90c4', note: 'Synthetic placeholder lineage B' },
  { id: 'SYN-C', color: '#2ea89a', note: 'Synthetic placeholder lineage C' },
  { id: 'SYN-D', color: '#c9a227', note: 'Synthetic placeholder lineage D' },
  { id: 'SYN-E', color: '#d9822b', note: 'Synthetic placeholder lineage E' },
];

export default function Genomic() {
  const { isDemo } = useMode();
  const [pathogen, setPathogen] = useState('sars-cov-2');
  const [view, setView] = useState('frequency');

  const freq = useMemo(() => {
    const r = rng('genomic:' + pathogen);
    const dates = isoWeeksBack(52);
    return dates.map((d, i) => {
      const t = i / dates.length;
      const raw = [
        Math.max(0, 0.55 - t * 0.5 + r() * 0.05),
        Math.max(0, 0.25 - t * 0.12 + r() * 0.04),
        Math.max(0, 0.1 + t * 0.35 + r() * 0.05),
        Math.max(0, 0.06 + t * 0.12 + r() * 0.03),
        Math.max(0, 0.04 + t * 0.08 + r() * 0.02),
      ];
      const s = raw.reduce((a, b) => a + b, 0);
      const row = { date: d };
      SYN_LINEAGES.forEach((l, j) => { row[l.id] = +((raw[j] / s) * 100).toFixed(1); });
      return row;
    });
  }, [pathogen]);

  const submissions = useMemo(() => synthSeries('genomic:sub:' + pathogen, { weeks: 52, level: 420, season: 0.25, disp: 0.35, trend: 0.4 }), [pathogen]);
  const latest = freq[freq.length - 1];

  const qc = useMemo(() => {
    const r = rng('genomic:qc:' + pathogen);
    return [
      { k: 'Sequences passing QC', v: `${(88 + r() * 8).toFixed(1)}%`, meter: 88 + r() * 8, color: 'var(--color-alert-green)' },
      { k: 'Mean genome coverage', v: `${(94 + r() * 4).toFixed(1)}%`, meter: 94 + r() * 4, color: 'var(--color-bw-primary)' },
      { k: 'Ambiguous base fraction', v: `${(1.2 + r() * 1.5).toFixed(2)}%`, meter: 12 + r() * 15, color: 'var(--color-alert-yellow)' },
      { k: 'Median submission lag', v: `${(11 + r() * 9).toFixed(0)} days`, meter: 55, color: 'var(--color-alert-orange)' },
    ];
  }, [pathogen]);

  const geoCoverage = {
    GBR: { state: 'GREEN', label: 'Sequencing stream configured', metrics: [{ k: 'Synthetic submissions/wk', v: '210' }] },
    USA: { state: 'GREEN', label: 'Sequencing stream configured', metrics: [{ k: 'Synthetic submissions/wk', v: '480' }] },
    ZAF: { state: 'YELLOW', label: 'Sparse submissions', metrics: [{ k: 'Synthetic submissions/wk', v: '24' }] },
    AUS: { state: 'GREEN', label: 'Sequencing stream configured', metrics: [{ k: 'Synthetic submissions/wk', v: '90' }] },
    NGA: { state: 'YELLOW', label: 'Sparse submissions', metrics: [{ k: 'Synthetic submissions/wk', v: '11' }] },
    BRA: { state: 'YELLOW', label: 'Sparse submissions', metrics: [{ k: 'Synthetic submissions/wk', v: '36' }] },
    IND: { state: 'YELLOW', label: 'Sparse submissions', metrics: [{ k: 'Synthetic submissions/wk', v: '52' }] },
    COD: { state: 'GREEN', availability: 'none', label: 'No sequencing stream configured', metrics: [] },
    ETH: { state: 'GREEN', availability: 'none', label: 'No sequencing stream configured', metrics: [] },
  };

  const genomicConnectors = CONNECTORS.filter((c) => c.stream === 'genomic');

  return (
    <>
      <PageHeader kicker="Module 10" title="Genomic Surveillance" evidence="PLAN"
        description="Architecture for lineage tracking, sequence quality assessment and emerging-variant signal detection from public genomic repositories. No sequence, mutation or variant discovery is generated by this prototype." />

      <Callout tone="danger" title="Fabrication prohibition for this module" icon={<Icons.ShieldAlert size={12} />}>
        Lineage labels below are placeholders (<span className="bw-num">SYN-A … SYN-E</span>) chosen so they cannot be
        confused with real nomenclature. No nucleotide or amino-acid sequence is displayed, stored or invented
        anywhere in this build, and no variant is claimed to be emerging, more transmissible or more severe.
      </Callout>

      {isDemo && <div className="my-3"><SimulatedBanner /></div>}

      <div className="mb-3 flex flex-wrap items-center gap-2">
        <span className="bw-label">Pathogen stream</span>
        <Segmented value={pathogen} onChange={setPathogen} options={[
          { value: 'sars-cov-2', label: 'SARS-CoV-2' }, { value: 'influenza-a', label: 'Influenza A' },
          { value: 'mpox', label: 'Mpox' }, { value: 'measles', label: 'Measles' },
        ]} />
        <span className="ml-auto"><Segmented size="xs" value={view} onChange={setView} options={[
          { value: 'frequency', label: 'Lineage frequency' }, { value: 'quality', label: 'Sequence QC' },
          { value: 'phylo', label: 'Phylogenetics' },
        ]} /></span>
      </div>

      <Grid cols="sm:grid-cols-2 xl:grid-cols-4" className="mb-3">
        <Stat label="Sequences ingested (synthetic)" value={submissions[submissions.length - 1].value.toLocaleString()} evidence="SIMULATED" sub="Latest synthetic week" />
        <Stat label="Placeholder lineages tracked" value={SYN_LINEAGES.length} evidence="SIMULATED" sub="Non-real labels" />
        <Stat label="Real variant calls made" value="0" evidence="ESTABLISHED" color="var(--color-bw-muted)" sub="By design — no genomic analysis is performed" />
        <Stat label="Repository connectors" value={`${genomicConnectors.length}`} evidence="ESTABLISHED" sub="0 configured" />
      </Grid>

      <Grid cols="xl:grid-cols-[1fr_350px]">
        <div className="min-w-0 space-y-3">
          {view === 'frequency' && (
            <>
              <Panel title="Placeholder lineage frequency over time" evidence="SIMULATED"
                subtitle="Stacked share of synthetic submissions. Frequency ≠ fitness: submission bias dominates raw shares.">
                <Stacked data={freq} keys={SYN_LINEAGES.map((l) => l.id)} colors={SYN_LINEAGES.map((l) => l.color)}
                  height={230} note="SIMULATED — placeholder lineages" />
                <div className="mt-2 flex flex-wrap gap-3">
                  {SYN_LINEAGES.map((l) => (
                    <span key={l.id} className="flex items-center gap-1.5 text-[10.5px] text-bw-muted">
                      <span className="h-2 w-2 rounded-sm" style={{ background: l.color }} />
                      {l.id} · {latest[l.id]}%
                    </span>
                  ))}
                </div>
              </Panel>

              <Panel title="Growth-advantage estimation" evidence="PLAN"
                subtitle="The analysis that would matter — and why it is not shown.">
                <NotImplemented what="Logistic growth-rate estimation with confidence intervals"
                  plan="Requires unbiased sampling assumptions, a documented denominator, and correction for submission lag and sequencing-strategy change. Producing a growth advantage from biased convenience samples is one of the most common errors in genomic epidemiology, and the prototype refuses to display one." />
                <div className="mt-2 grid gap-2 sm:grid-cols-3">
                  {['Relative growth rate', 'Doubling time', 'Selection coefficient'].map((m) => (
                    <div key={m} className="rounded-sm border border-dashed border-bw-line2 px-2 py-2">
                      <div className="bw-label">{m}</div>
                      <div className="mt-1"><Awaiting label={SAFE_LANGUAGE.awaitingExperiment} /></div>
                    </div>
                  ))}
                </div>
              </Panel>

              <Panel title="Mutation profile" evidence="PLAN"
                subtitle="Reserved for real repository data.">
                <NoData reason="No mutation table is displayed because no genomic data is connected. Fabricating mutation positions would be scientifically unacceptable even under a SIMULATED label." />
                <div className="mt-2 text-[11px] leading-relaxed text-bw-muted">
                  When a connector is configured, this panel will render: substitutions by genome position, amino-acid
                  changes by protein, prevalence per lineage, and a per-site coverage indicator so that absence of a
                  mutation call can be distinguished from absence of coverage.
                </div>
              </Panel>
            </>
          )}

          {view === 'quality' && (
            <>
              <Panel title="Sequence quality control" evidence="SIMULATED"
                subtitle="QC gates every sequence must pass before entering any frequency calculation.">
                <div className="space-y-3">
                  {qc.map((q) => <Meter key={q.k} label={q.k} right={q.v} value={q.meter} color={q.color} />)}
                </div>
                <div className="mt-3">
                  <Table dense columns={[
                    { key: 'gate', header: 'QC gate' }, { key: 'rule', header: 'Rule' },
                    { key: 'action', header: 'Action on failure' },
                  ]} rows={[
                    { gate: 'Genome coverage', rule: '≥ 90% of reference length', action: 'Exclude from frequency estimates; retain in archive' },
                    { gate: 'Ambiguous bases', rule: '≤ 5% N content', action: 'Exclude from lineage assignment' },
                    { gate: 'Collection date', rule: 'Present and plausible', action: 'Exclude from temporal analysis' },
                    { gate: 'Geography', rule: 'Resolvable to admin-1 or country', action: 'Exclude from geographic analysis' },
                    { gate: 'Duplicate detection', rule: 'Hash of sequence + metadata', action: 'Retain first, flag subsequent' },
                    { gate: 'Submission lag', rule: 'Recorded, not filtered', action: 'Down-weight recent weeks in trend estimates' },
                  ]} />
                </div>
              </Panel>

              <Panel title="Submission cadence" evidence="SIMULATED"
                subtitle="Sequences submitted per week. Cadence changes create apparent lineage shifts that are purely artefactual.">
                <Bars data={submissions.slice(-26).map((s) => ({ name: s.date.slice(5), value: s.value }))}
                  height={170} color="var(--color-bw-genomic)" note="SIMULATED — synthetic submission counts" />
              </Panel>
            </>
          )}

          {view === 'phylo' && (
            <Panel title="Phylogenetic analysis interface" evidence="PLAN">
              <NotImplemented what="Interactive phylogenetic tree (Auspice-compatible)"
                plan="Design target: load an Auspice v2 JSON from a public Nextstrain build, render a time-scaled tree with tip metadata (collection date, geography, lineage), support clade collapse, colour-by, and a linked map. Tree inference itself would remain the responsibility of the upstream build — this platform would visualise and interrogate, not infer." />
              <Grid cols="md:grid-cols-2" className="mt-3">
                <div className="rounded-md border border-dashed border-bw-line2 p-6 text-center">
                  <Icons.GitFork size={28} className="mx-auto text-bw-line2" strokeWidth={1.2} />
                  <div className="mt-2 font-mono text-[10px] tracking-[0.12em] text-bw-dim">TREE VIEWER — NOT IMPLEMENTED</div>
                  <p className="mx-auto mt-1.5 max-w-xs text-[11px] leading-snug text-bw-dim">
                    No tree is rendered from synthetic data: a fabricated phylogeny implies evolutionary
                    relationships that do not exist.
                  </p>
                </div>
                <div className="space-y-2">
                  {[['Time-scaled tree', 'Auspice JSON v2'], ['Tip metadata linkage', 'collection date · geography · lineage'],
                    ['Clade frequency panel', 'derived from tree, not from raw submissions'], ['Geographic transmission view', 'requires strong caveats on sampling'],
                    ['Ancestral state reconstruction', 'upstream responsibility']].map(([k, v]) => (
                    <div key={k} className="rounded-sm border border-bw-line bg-bw-panel2/40 px-2.5 py-2">
                      <div className="text-[11.5px] text-bw-text">{k}</div>
                      <div className="mt-0.5 text-[10px] text-bw-dim">{v}</div>
                    </div>
                  ))}
                </div>
              </Grid>
            </Panel>
          )}

          <Panel title="Geographic sequencing capacity" evidence="SIMULATED"
            subtitle="Where sequences come from is a map of capacity, not of viral diversity.">
            <WorldMap values={geoCoverage} height={260} />
            <div className="mt-2"><MapLegend compact /></div>
            <p className="mt-2 text-[10.5px] leading-relaxed text-bw-dim">
              Any global lineage frequency computed from these submissions is dominated by the few territories that
              sequence most. This is the single largest bias in genomic surveillance and no statistical correction
              fully removes it.
            </p>
          </Panel>
        </div>

        {/* ---------- Side rail ---------- */}
        <div className="flex min-w-0 flex-col gap-3">
          <Panel title="Repository connectors" evidence="ESTABLISHED">
            <div className="space-y-2">
              {genomicConnectors.map((c) => (
                <div key={c.id} className="rounded-sm border border-bw-line bg-bw-panel2/40 p-2.5">
                  <div className="text-[11.5px] text-bw-text">{c.name}</div>
                  <div className="mt-1 space-y-0.5 text-[10px] text-bw-dim">
                    <div>Auth: {c.auth}</div>
                    <div>Format: {c.format}</div>
                    <div>Licence: {c.license}</div>
                  </div>
                  <div className="mt-1.5 font-mono text-[9px] tracking-[0.08em]"
                    style={{ color: c.status === 'blocked' ? 'var(--color-alert-yellow)' : 'var(--color-bw-data)' }}>
                    {c.status === 'blocked' ? 'ACCESS RESTRICTED — AGREEMENT REQUIRED' : SAFE_LANGUAGE.connectorAvailable}
                  </div>
                  {c.caveats && <p className="mt-1 border-t border-bw-line/60 pt-1 text-[10px] leading-snug text-bw-muted">{c.caveats}</p>}
                </div>
              ))}
            </div>
          </Panel>

          <Panel title="Emerging-variant signal design" evidence="PLAN"
            subtitle="What a defensible genomic signal would require.">
            <ol className="space-y-1.5 text-[11px] text-bw-muted">
              {['Denominator-aware frequency (sequences per case, per region)',
                'Explicit submission-lag model before any trend is fitted',
                'Growth estimate with uncertainty, not a point value',
                'Concordance requirement with an independent stream (cases, hospitalisations, wastewater)',
                'Phenotypic caution: sequence change ≠ transmissibility or severity change',
                'Human genomic-epidemiology review before any signal is surfaced'].map((x, i) => (
                <li key={x} className="flex gap-2"><span className="bw-num text-bw-dim">{i + 1}.</span>{x}</li>
              ))}
            </ol>
          </Panel>

          <Panel title="Biosecurity posture" evidence="ESTABLISHED">
            <ul className="space-y-1.5 text-[11px] leading-relaxed text-bw-muted">
              {['No sequence data is generated, stored or displayed by this prototype.',
                'No enhancement-, gain-of-function- or design-related capability exists or is planned.',
                'Analysis scope is restricted to lineage-frequency and quality metadata from public repositories.',
                'Any future integration must pass an institutional biosecurity review before configuration.'].map((x) => (
                <li key={x} className="flex gap-1.5"><Icons.ShieldCheck size={12} className="mt-[2px] shrink-0 text-[var(--color-alert-green)]" />{x}</li>
              ))}
            </ul>
          </Panel>

          <Panel title="Module state" evidence="ESTABLISHED" dense>
            <KV items={[
              { k: 'Implementation', v: 'Interface only' },
              { k: 'Data bound', v: 'None' },
              { k: 'Sequences held', v: '0' },
              { k: 'Variant calls', v: '0' },
              { k: 'Last update', v: fmtTs() },
            ]} />
          </Panel>
        </div>
      </Grid>
    </>
  );
}
