"""
BIOWATCH-AI — connector registry (server-side mirror of the frontend registry).

Listing a source implies no affiliation, endorsement or granted access; each
remains subject to its own licence and terms of use.

No connector is configured in this prototype. Unconfigured sources are reported
as such and are NEVER substituted with synthetic values presented as live.
"""
from __future__ import annotations

CONNECTORS: list[dict] = [
    {
        "id": "who-gho",
        "name": "WHO Global Health Observatory (GHO)",
        "org": "World Health Organization",
        "type": "Epidemiological indicators",
        "stream": "epi",
        "url": "https://ghoapi.azureedge.net/api/",
        "docs": "https://www.who.int/data/gho/info/gho-odata-api",
        "auth": "None (public OData endpoint)",
        "format": "OData / JSON",
        "frequency": "Irregular — indicator dependent",
        "granularity": "Country · year (mostly annual)",
        "license": "WHO data terms; attribution required. Verify per-indicator terms.",
        "status": "available",
        "lastUpdate": None,
        "error": None,
        "caveats": "Annual granularity is generally too coarse for weekly signal detection; useful as denominator/context."
    },
    {
        "id": "who-don",
        "name": "WHO Disease Outbreak News (DON)",
        "org": "World Health Organization",
        "type": "Event-based reports",
        "stream": "event",
        "url": "https://www.who.int/emergencies/disease-outbreak-news",
        "docs": "https://www.who.int/emergencies/disease-outbreak-news",
        "auth": "None (public web/RSS)",
        "format": "HTML / RSS → structured extraction",
        "frequency": "Event-driven, irregular",
        "granularity": "Event · country · date",
        "license": "WHO content terms; attribution and non-alteration requirements apply.",
        "status": "available",
        "lastUpdate": None,
        "error": None,
        "caveats": "Reference/verification corpus only. DON publication lags detection and must never be used as a real-time detector input without explicit lag handling."
    },
    {
        "id": "cdc-socrata",
        "name": "US CDC open data (data.cdc.gov)",
        "org": "US Centers for Disease Control and Prevention",
        "type": "Surveillance datasets",
        "stream": "epi",
        "url": "https://data.cdc.gov/resource/{dataset_id}.json",
        "docs": "https://dev.socrata.com/",
        "auth": "Optional app token (higher rate limit)",
        "format": "Socrata SODA / JSON / CSV",
        "frequency": "Dataset dependent — weekly for several syndromic sets",
        "granularity": "State · week (varies)",
        "license": "Generally US public domain; confirm per dataset.",
        "status": "available",
        "lastUpdate": None,
        "error": None,
        "caveats": "Schema and revision policy vary by dataset; back-revision of recent weeks is common."
    },
    {
        "id": "ecdc-atlas",
        "name": "ECDC Surveillance Atlas exports",
        "org": "European Centre for Disease Prevention and Control",
        "type": "Notifiable disease surveillance",
        "stream": "epi",
        "url": "https://atlas.ecdc.europa.eu/public/index.aspx",
        "docs": "https://www.ecdc.europa.eu/en/publications-data",
        "auth": "None (bulk export)",
        "format": "CSV export",
        "frequency": "Periodic (monthly/annual by disease)",
        "granularity": "Country · month/year",
        "license": "ECDC re-use policy; attribution required.",
        "status": "available",
        "lastUpdate": None,
        "error": None,
        "caveats": "Programmatic API coverage is limited; scheduled export ingestion is the realistic pattern."
    },
    {
        "id": "owid",
        "name": "Our World in Data — health datasets",
        "org": "Our World in Data / Global Change Data Lab",
        "type": "Curated aggregate indicators",
        "stream": "epi",
        "url": "https://catalog.ourworldindata.org/",
        "docs": "https://docs.owid.io/projects/etl/api/",
        "auth": "None",
        "format": "CSV / Parquet",
        "frequency": "Dataset dependent",
        "granularity": "Country · day/week/year",
        "license": "Predominantly CC BY 4.0; upstream source licences also apply.",
        "status": "available",
        "lastUpdate": None,
        "error": None,
        "caveats": "A curated re-publication layer — always cite the upstream source, and expect harmonisation choices to affect series shape."
    },
    {
        "id": "ncbi-eutils",
        "name": "NCBI E-utilities / Datasets",
        "org": "US National Center for Biotechnology Information",
        "type": "Pathogen sequence metadata",
        "stream": "genomic",
        "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/",
        "docs": "https://www.ncbi.nlm.nih.gov/books/NBK25501/",
        "auth": "Optional API key (raises rate limit to 10 req/s)",
        "format": "XML / JSON / FASTA",
        "frequency": "Continuous submission",
        "granularity": "Accession · collection date · geography",
        "license": "Public domain data; NCBI usage policies and rate limits apply.",
        "status": "available",
        "lastUpdate": None,
        "error": None,
        "caveats": "Submission date ≠ collection date. Sequencing effort is highly non-uniform; frequency estimates from raw submissions are severely biased."
    },
    {
        "id": "nextstrain",
        "name": "Nextstrain open builds",
        "org": "Nextstrain",
        "type": "Phylogenetic builds & clade assignment",
        "stream": "genomic",
        "url": "https://data.nextstrain.org/",
        "docs": "https://docs.nextstrain.org/",
        "auth": "None for public builds",
        "format": "Auspice JSON v2",
        "frequency": "Build dependent (often weekly)",
        "granularity": "Tree · node · metadata",
        "license": "Open builds; check individual build data provenance and acknowledgements.",
        "status": "available",
        "lastUpdate": None,
        "error": None,
        "caveats": "Builds are subsampled for tractability; subsampling is not a random sample of circulating diversity."
    },
    {
        "id": "gisaid",
        "name": "GISAID EpiCoV / EpiFlu",
        "org": "GISAID",
        "type": "Pathogen genomic data",
        "stream": "genomic",
        "url": "https://gisaid.org/",
        "docs": "https://gisaid.org/",
        "auth": "Registered access + data-access agreement",
        "format": "Per-agreement feed",
        "frequency": "Continuous",
        "granularity": "Sequence · metadata",
        "license": "Access governed by the GISAID Database Access Agreement; redistribution restricted.",
        "status": "blocked",
        "lastUpdate": None,
        "error": "Data-access agreement not executed for this prototype. No data requested or stored.",
        "caveats": "Terms prohibit the redistribution patterns a public dashboard would imply. Aggregate-only use must be legally reviewed before enabling."
    },
    {
        "id": "wastewater-open",
        "name": "Open wastewater surveillance programmes",
        "org": "Various national/regional programmes",
        "type": "Environmental pathogen concentration",
        "stream": "env",
        "url": "Programme-specific endpoints (e.g. national open-data portals)",
        "docs": "—",
        "auth": "Varies by programme",
        "format": "CSV / JSON",
        "frequency": "Typically weekly or twice-weekly",
        "granularity": "Sampling site · date",
        "license": "Programme-specific; several are open government licences.",
        "status": "unconfigured",
        "lastUpdate": None,
        "error": None,
        "caveats": "Concentrations require flow/population normalisation; assay and site changes routinely produce step artefacts that mimic signals."
    },
    {
        "id": "ncdc-ng",
        "name": "Nigeria CDC public situation reports",
        "org": "Nigeria Centre for Disease Control and Prevention",
        "type": "National epidemiological reports",
        "stream": "epi",
        "url": "https://ncdc.gov.ng/reports",
        "docs": "https://ncdc.gov.ng/",
        "auth": "None (published reports)",
        "format": "PDF / HTML → structured extraction required",
        "frequency": "Weekly / monthly by programme",
        "granularity": "State · epidemiological week",
        "license": "Public reports; attribution required. Confirm re-use terms.",
        "status": "unconfigured",
        "lastUpdate": None,
        "error": None,
        "caveats": "No machine-readable API is documented; PDF extraction is fragile and must be validated per report layout before any analytical use."
    },
    {
        "id": "africa-cdc",
        "name": "Africa CDC public dashboards",
        "org": "Africa Centres for Disease Control and Prevention",
        "type": "Regional epidemiological summaries",
        "stream": "epi",
        "url": "https://africacdc.org/",
        "docs": "https://africacdc.org/institutes/",
        "auth": "None (published dashboards)",
        "format": "HTML / dashboard exports",
        "frequency": "Weekly summaries where published",
        "granularity": "Country · week",
        "license": "Attribution required; confirm re-use terms.",
        "status": "unconfigured",
        "lastUpdate": None,
        "error": None,
        "caveats": "Member-state reporting completeness varies substantially; absence of data must never be rendered as absence of disease."
    },
    {
        "id": "promed",
        "name": "Event-based media/report feeds (ProMED-style)",
        "org": "Various",
        "type": "Unverified event reports",
        "stream": "event",
        "url": "Feed-specific",
        "docs": "—",
        "auth": "Varies; some require subscription",
        "format": "RSS / e-mail digest → NLP extraction",
        "frequency": "Continuous",
        "granularity": "Report · location · date",
        "license": "Varies; several prohibit redistribution.",
        "status": "planned",
        "lastUpdate": None,
        "error": None,
        "caveats": "Enters the system as UNVERIFIED by definition. Must never be auto-promoted to a confirmed event."
    },
    {
        "id": "era5-climate",
        "name": "Open climate reanalysis (temperature/precipitation)",
        "org": "Copernicus / national meteorological services",
        "type": "Environmental covariates",
        "stream": "env",
        "url": "https://cds.climate.copernicus.eu/",
        "docs": "https://cds.climate.copernicus.eu/how-to-api",
        "auth": "Free registration + API key",
        "format": "NetCDF / GRIB",
        "frequency": "Daily/monthly reanalysis",
        "granularity": "Grid cell · day",
        "license": "Copernicus licence; attribution required.",
        "status": "unconfigured",
        "lastUpdate": None,
        "error": None,
        "caveats": "Covariate only. Climate association is confounded with seasonality already captured by the baseline."
    },
    {
        "id": "who-flunet",
        "name": "WHO FluNet / FluID",
        "org": "World Health Organization",
        "type": "Virological & syndromic influenza surveillance",
        "stream": "lab",
        "url": "https://www.who.int/tools/flunet",
        "docs": "https://www.who.int/tools/flunet",
        "auth": "None (public export)",
        "format": "CSV export",
        "frequency": "Weekly",
        "granularity": "Country · epidemiological week",
        "license": "WHO data terms; attribution required.",
        "status": "available",
        "lastUpdate": None,
        "error": None,
        "caveats": "One of the few genuinely weekly global streams — the most realistic first target for a baseline-vs-model experiment."
    }
]
